project: 
  type: website
  
website: 
  page-navigation: true
  title: "Book of abstracts, Swedish Bioinformatics Workshop 2024" 
  site-url: "https://www.sbw2024.org/" 
  repo-url: https://github.com/SBW2024/abstracts_quarto
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: ""

execute:
  freeze: auto

format:
  html:
    theme:
      light: [flatly]
      dark: [darkly]
    code-copy: true
    linkcolor: "#539180"
    code-overflow: wrap
    toc: false

filters:
  - quarto

  
