---
title: "Interactome analysis of tight junction protein CLDN6 in regenerating salamander hearts"
author: "Inika Prasad"
authors:
  - name: Inika Prasad
    affiliations:
      - ref: u1
  - name: Sofia Kagioglou
    affiliations:
      - ref: u1
  - name: Myra Chavez Rosas
    affiliations:
      - ref: u1
  - name: Elif Eroglu
    affiliations:
      - ref: u1
affiliations:
  - id: u1
    name: Department of Cell and Molecular Biology, Karolinska Institutet 
date: 2024-11-04T14:45:12
categories:
  - poster session
  - monday
---

ABSTRACT:

Despite a shared response to acute ischemic injury in the heart, regenerative potential varies greatly between animals. Salamander species *Pleurodeles waltl* can regenerate its heart upon cryoinjury. Mechanistically, dynamic tight junction remodeling in the epicardium – the outer cell layer covering the heart – is required for cardiac regeneration. CLAUDIN-6 (CLDN6), an evolutionarily conserved tight junction protein, is expressed in the epicardium during homeostasis.  

Interestingly, a divergent CLDN6 isoform with a 50 amino-acid-long extension of the cytoplasmic N-terminus, termed CLDN6-long, is expressed in the epicardium in response to injury and its expression persists throughout regeneration. However, the functional role of this isoform in mediating heart regeneration remains elusive.  

Here, we adapted a novel protein interactomics method called PrISMa (Protein Interaction Screen on a Peptide Matrix) to identify the protein-interaction partners of CLDN6-long, as well as the importance of predicted phosphorylation sites. The amino acid sequence of the CLDN6-long N-terminus and C-terminus was used to generate a library of 15-amino acid-long overlapping peptides with a 5-amino acid window shift mapping the cytosolic tails. 19 peptides (unmodified and modified) were synthesized by spot synthesis on a cellulose membrane that was thereafter incubated with nuclei-depleted heart tissue lysate from uninjured and injured hearts. Interacting partners were identified using mass spectrometry and an analysis pipeline has been established. By exploring this dataset, we expect to elucidate regeneration-specific roles of CLDN6-long and identify targetable processes in humans to aid recovery from ischemic heart injury. 


